
POST http://localhost:3000/events.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2OTM4NjMyMDd9.mQx0xqsdoUEt4SbzHVV3WEpO43iMX-5qID4xkxbOIWU
Content-Type: application/json

{
  "sport": "test",
  "distance": 2,
  "duration": 4.0,
  "details": "test",
  "city": "test",
  "zipcode": 12212,
  "latitude": 99999.0,
  "longtitude": 11111.0,
  "image": "test"
}

### 
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
 "email": "test@test.com",
 "password": "password"
}
